### ISSUE TITLE
Integration with Elfinder

### ISSUE THREAD

**Issue by chrisjohnstone** [ckrack/ckeditor_imageresponsive#3]
Hi,

Firstly, thanks for writing the package.

I'm trying to integrate this into my Elfinder filebrowser but I'm unsure where the callback needs to go.

I'm using Laravel and this package (https://github.com/barryvdh/laravel-elfinder) and in my ckeditor4 file I have the following:

```
$().ready(function() {
            var funcNum = getUrlParam('CKEditorFuncNum');

            var elf = $('#elfinder').elfinder({
                // set your elFinder options here
                <?php if($locale){ ?>
                    lang: '<?= $locale ?>', // locale
                <?php } ?>
                customData: {
                    _token: '<?= csrf_token() ?>'
                },
                url: '<?= route("elfinder.connector") ?>',  // connector URL
	            height:800,
                getFileCallback : function(file) {
                    window.opener.CKEDITOR.tools.callFunction(funcNum, file.url);
                   -- Tried inserting here --
                    window.close();
                },
	       ...
}).elfinder('instance');
```

I tried placed the callback in there but to no avail. I get the error _Error in `getFileCallback`.
Cannot read property 'tools' of undefined_

Am I a million miles away?

**Comment by ckrack** [comment]
Hi @chrisjohnstone, it's been a while since I've worked with this.
Did you check with devtools, whether `window.opener.CKEDITOR` is set at all?
I don't know the laravel package you mentioned, but if it's using an iframe you might have to use `window.parent`.

**Comment by chrisjohnstone** [comment]
Hi @ckrack, good shout. Although I expect I would have noticed if it wasn't, I'll go and double check!

**Comment by chrisjohnstone** [comment]
I managed to solve this. Where your example is looking for a dialog called 'imageresponsive' I had to change this to 'image2'.

I don't know why the dialog wasn't being labelled imageresponsive - perhaps the way my CKEditor was built but it's working now.
